# frozen_string_literal: true
require "date"
require "json"
require "sinatra/base"
require "tilt/erb"
require "sinatra/param"
require "raven"
require "mechanize"
require "excon"

require "movies_api/resource"
require "movies_api/cinema"
require "movies_api/film"
require "movies_api/showing"
require "movies_api/find_any_film"
require "movies_api/app"
